"use strict";
const KEY="yvaStudioDatosV4";
const BASE={nombre:"YVA STUDIO",dias:25,descuentoCumple:10,largos:{corto:25,medio:35,largo:45},servicios:[{id:"builder",nombre:"Builder Gel",modo:"largo",precio:0,fijo:true},{id:"polygel",nombre:"Polygel",modo:"largo",precio:0,fijo:true},{id:"soft",nombre:"Soft Gel",modo:"largo",precio:0,fijo:true},{id:"dual",nombre:"Dual System",modo:"largo",precio:0,fijo:true},{id:"shellac",nombre:"Shellac",modo:"fijo",precio:20,fijo:true},{id:"pedi_spa",nombre:"Pedi Spa",modo:"fijo",precio:35,fijo:true},{id:"pedi_express",nombre:"Pedi Express",modo:"fijo",precio:20,fijo:true}],extras:[{id:"french",nombre:"French",precio:5,fijo:true},{id:"cateye",nombre:"Cat Eye",precio:5,fijo:true},{id:"aura",nombre:"Aura",precio:10,fijo:true},{id:"cristales",nombre:"Cristales",precio:5,fijo:true},{id:"retiro",nombre:"Retiro previo",precio:8,fijo:true}]};
let data=load(),calendar=null,editing=null,origin=null,calcTotal=0;
document.addEventListener("DOMContentLoaded",()=>{migrate();ensureDefaults();bind();fillServices();loadConfig();buildFortnights();initCalendar();refresh()});
function fresh(){return{citas:[],config:JSON.parse(JSON.stringify(BASE))}}
function load(){try{let d=JSON.parse(localStorage.getItem(KEY)||"null");return d?{citas:Array.isArray(d.citas)?d.citas:[],config:{...BASE,...d.config,largos:{...BASE.largos,...(d.config?.largos||{})},servicios:d.config?.servicios?.length?d.config.servicios:BASE.servicios,extras:d.config?.extras?.length?d.config.extras:BASE.extras}}:fresh()}catch{return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function migrate(){if(!data.citas.length){try{const v2=JSON.parse(localStorage.getItem("yvaStudioDatosV2")||"null"),old=JSON.parse(localStorage.getItem("citas")||"[]");if(v2?.citas?.length)data.citas=v2.citas;else if(Array.isArray(old))data.citas=old}catch{}}data.citas=data.citas.map(c=>({id:Number(c.id)||id(),nombre:String(c.nombre||"").trim(),fecha:c.fecha||"",hora:c.hora||"09:00",servicio:c.servicio||"Builder Gel",total:Number(c.total||0),notas:c.notas||"",cumpleanos:c.cumpleanos||"",estado:["pendiente","completada","cancelada"].includes(c.estado)?c.estado:"pendiente",fechaCompletada:c.fechaCompletada||null,mantenimientoAgendado:c.mantenimientoAgendado===true,citaOrigenId:c.citaOrigenId||null}));save()}
function ensureDefaults(){data.config.descuentoCumple=Number(data.config.descuentoCumple??10);BASE.servicios.forEach(base=>{if(!data.config.servicios.some(s=>s.id===base.id||s.nombre.toLowerCase()===base.nombre.toLowerCase()))data.config.servicios.push(JSON.parse(JSON.stringify(base)))});BASE.extras.forEach(base=>{if(!data.config.extras.some(x=>x.id===base.id||x.nombre.toLowerCase()===base.nombre.toLowerCase()))data.config.extras.push(JSON.parse(JSON.stringify(base)))});save()}
function bind(){document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>show(b.dataset.page));["topNew","dashNew","agendaNew"].forEach(x=>$(x).onclick=()=>openNew());$("closeAppointment").onclick=$("cancelAppointment").onclick=closeAppointment;$("appointmentForm").onsubmit=saveAppointment;$("appointmentModal").onclick=e=>{if(e.target.id==="appointmentModal")closeAppointment()};$("closeHistory").onclick=closeHistory;$("historyModal").onclick=e=>{if(e.target.id==="historyModal")closeHistory()};$("clientSearch").oninput=renderClients;$("fortnightSelect").onchange=renderFinance;$("addService").onclick=addService;$("addExtra").onclick=addExtra;$("quoteToAppointment").onclick=quoteToAppointment;$("clearCalc").onclick=clearCalc;$("saveConfig").onclick=saveConfig;$("exportData").onclick=exportData;$("resetCatalog").onclick=resetCatalog;$("deleteAll").onclick=deleteAll;["calcService","calcLength","manualExtra","discount","birthdayDiscount"].forEach(x=>$(x).oninput=calculate)}
function show(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.remove("active"));$(p)?.classList.add("active");document.querySelector(`[data-page="${p}"]`)?.classList.add("active");$("pageTitle").textContent={dashboard:"Dashboard",agenda:"Agenda",clientes:"Clientas",recordatorios:"Recordatorios",finanzas:"Finanzas",calculadora:"Calculadora",configuracion:"Configuración"}[p]||"YVA STUDIO";if(p==="agenda"&&calendar)setTimeout(()=>calendar.updateSize(),100);if(p==="clientes")renderClients();if(p==="finanzas")renderFinance();if(p==="calculadora"){renderCatalog();calculate()}}
function initCalendar(){calendar=new FullCalendar.Calendar($("calendar"),{locale:"es",initialView:"dayGridMonth",height:"auto",headerToolbar:{left:"prev,next today",center:"title",right:"dayGridMonth,timeGridWeek,timeGridDay"},buttonText:{today:"Hoy",month:"Mes",week:"Semana",day:"Día"},events:events(),eventClick:i=>editAppointment(Number(i.event.id)),dateClick:i=>openNew(i.dateStr)});calendar.render()}
function events(){return data.citas.map(c=>({id:String(c.id),title:`${c.nombre} · ${c.servicio}`,start:`${c.fecha}T${c.hora}`,backgroundColor:c.estado==="completada"?"#39704a":c.estado==="cancelada"?"#888":"#540212",borderColor:"transparent"}))}
function updateCalendar(){if(!calendar)return;calendar.removeAllEvents();events().forEach(e=>calendar.addEvent(e))}
function fillServices(selected=""){const opts=data.config.servicios.map(s=>`<option value="${esc(s.nombre)}">${esc(s.nombre)}</option>`).join("");$("service").innerHTML=opts;const old=$("calcService").value;$("calcService").innerHTML=opts;if(selected){$("service").value=selected;$("calcService").value=selected}else if(data.config.servicios.some(s=>s.nombre===old))$("calcService").value=old;renderExtras()}
function renderExtras(){$("calcExtras").innerHTML=data.config.extras.map(x=>`<label class="check"><input type="checkbox" data-extra="${x.id}"><span>${esc(x.nombre)} · ${money(x.precio)}</span></label>`).join("");document.querySelectorAll("#calcExtras input").forEach(i=>i.oninput=calculate)}
function openNew(date=""){editing=null;origin=null;$("appointmentForm").reset();fillServices();$("appointmentModalTitle").textContent="Nueva cita";$("date").value=date||today();$("time").value="09:00";openModal("appointmentModal")}
function openModal(x){$(x).classList.add("open")}
function closeAppointment(){$("appointmentModal").classList.remove("open");editing=null;origin=null}
function saveAppointment(e){e.preventDefault();const p={nombre:val("name").trim(),fecha:val("date"),hora:val("time"),servicio:val("service"),total:Number(val("total")||0),notas:val("notes").trim(),cumpleanos:val("birthday")};if(!p.nombre||!p.fecha||!p.hora)return alert("Completa nombre, fecha y hora.");if(editing)Object.assign(find(editing),p);else{data.citas.push({id:id(),...p,estado:"pendiente",fechaCompletada:null,mantenimientoAgendado:false,citaOrigenId:origin});if(origin){const o=find(origin);if(o)o.mantenimientoAgendado=true}}save();closeAppointment();refresh()}
function editAppointment(i){const c=find(i);if(!c)return;editing=i;origin=null;fillServices(c.servicio);["name","date","time","birthday","service","total","notes"].forEach((x,n)=>$(x).value=[c.nombre,c.fecha,c.hora,c.cumpleanos||"",c.servicio,c.total,c.notas][n]);$("appointmentModalTitle").textContent="Editar cita";openModal("appointmentModal")}
function completeAppointment(i){const c=find(i);if(c&&confirm(`¿Marcar la cita de ${c.nombre} como completada?`)){c.estado="completada";c.fechaCompletada=today();save();refresh()}}
function cancelAppointment(i){const c=find(i);if(c&&confirm(`¿Cancelar la cita de ${c.nombre}?`)){c.estado="cancelada";save();refresh()}}
function deleteAppointment(i){const c=find(i);if(c&&confirm(`¿Eliminar definitivamente la cita de ${c.nombre}?`)){data.citas=data.citas.filter(x=>x.id!==i);save();closeHistory();refresh()}}
function find(i){return data.citas.find(c=>c.id===Number(i))}
function renderAppointments(){const a=[...data.citas].sort((x,y)=>dateTime(y)-dateTime(x));$("appointmentList").innerHTML=a.length?a.map(c=>`<article class="appointment ${c.estado==="completada"?"completed":c.estado==="cancelada"?"canceled":""}"><div class="appointment-top"><div><h4>${esc(c.nombre)}</h4><span class="status ${c.estado==="pendiente"?"pending":c.estado==="completada"?"completed":"canceled"}">${state(c.estado)}</span></div><strong class="appointment-price">${money(c.total)}</strong></div><div class="details"><p><strong>Fecha:</strong> ${formatDate(c.fecha)}</p><p><strong>Hora:</strong> ${formatTime(c.hora)}</p><p><strong>Servicio:</strong> ${esc(c.servicio)}</p>${c.notas?`<p><strong>Notas:</strong> ${esc(c.notas)}</p>`:""}</div><div class="actions">${c.estado==="pendiente"?`<button class="complete-btn" onclick="completeAppointment(${c.id})">Completar</button><button class="cancel-btn" onclick="cancelAppointment(${c.id})">Cancelar</button>`:""}<button class="edit-btn" onclick="editAppointment(${c.id})">Editar</button><button class="delete-btn" onclick="deleteAppointment(${c.id})">Eliminar</button></div></article>`).join(""):'<p class="empty">No hay citas registradas.</p>'}
function clientGroups(){const g={};data.citas.forEach(c=>{const k=norm(c.nombre);if(!k)return;if(!g[k])g[k]={nombre:c.nombre,citas:[],cumpleanos:""};g[k].citas.push(c);if(c.cumpleanos)g[k].cumpleanos=c.cumpleanos});return Object.values(g)}
function renderClients(){const q=val("clientSearch").trim().toLowerCase(),a=clientGroups().filter(x=>x.nombre.toLowerCase().includes(q)).sort((x,y)=>x.nombre.localeCompare(y.nombre,"es"));$("clientList").innerHTML=a.length?a.map(x=>`<div class="client-row"><h3>${esc(x.nombre)}</h3><button class="secondary" onclick="openHistory('${encodeURIComponent(norm(x.nombre))}')">Ver historial</button></div>`).join(""):'<p class="empty">No se encontraron clientas.</p>'}
function openHistory(k){const c=clientGroups().find(x=>norm(x.nombre)===decodeURIComponent(k));if(!c)return;const h=[...c.citas].sort((x,y)=>dateTime(y)-dateTime(x)),done=h.filter(x=>x.estado==="completada"),pending=h.filter(x=>x.estado==="pendiente"),canceled=h.filter(x=>x.estado==="cancelada");$("historyName").textContent=c.nombre;$("historySummary").innerHTML=`<div class="history-stats"><div><span>Total invertido</span><strong>${money(done.reduce((s,x)=>s+x.total,0))}</strong></div><div><span>Completadas</span><strong>${done.length}</strong></div><div><span>Pendientes</span><strong>${pending.length}</strong></div><div><span>Canceladas</span><strong>${canceled.length}</strong></div></div>`;$("historyBody").innerHTML=h.map(x=>`<tr><td>${formatDate(x.fecha)}</td><td>${formatTime(x.hora)}</td><td>${esc(x.servicio)}</td><td><span class="status ${x.estado==="pendiente"?"pending":x.estado==="completada"?"completed":"canceled"}">${state(x.estado)}</span></td><td>${money(x.total)}</td><td><div class="table-actions"><button class="edit-btn" onclick="editAppointment(${x.id})">Editar</button><button class="delete-btn" onclick="deleteAppointment(${x.id})">Eliminar</button></div></td></tr>`).join("");openModal("historyModal")}
function closeHistory(){$("historyModal").classList.remove("open")}
function reminders(){const h=startDay(new Date());return data.citas.filter(c=>c.estado!=="cancelada"&&!c.mantenimientoAgendado&&c.fecha&&addDays(c.fecha,data.config.dias)<=h)}
function renderReminders(){const a=reminders();$("reminderList").innerHTML=a.length?a.map(c=>{const f=addDays(c.fecha,data.config.dias),d=daysBetween(f,new Date());return `<article class="reminder"><div><h3>${esc(c.nombre)}</h3><p><strong>Servicio:</strong> ${esc(c.servicio)}</p><p><strong>Última cita:</strong> ${formatDate(c.fecha)}</p><p><strong>Fecha recomendada:</strong> ${formatDate(dateText(f))}</p><span class="late">${d===0?"Mantenimiento para hoy":`${d} días de seguimiento`}</span></div><button class="primary" onclick="scheduleMaintenance(${c.id})">Agendar mantenimiento</button></article>`}).join(""):'<div class="card"><p class="empty">No hay mantenimientos pendientes.</p></div>'}
function scheduleMaintenance(i){const c=find(i);if(!c)return;origin=i;editing=null;$("appointmentForm").reset();fillServices(c.servicio);$("name").value=c.nombre;$("service").value=c.servicio;$("total").value=c.total;$("date").value=today();$("time").value="09:00";$("notes").value=`Mantenimiento de la cita del ${formatDate(c.fecha)}.`;$("appointmentModalTitle").textContent="Agendar mantenimiento";show("agenda");openModal("appointmentModal")}
function renderDashboard(){const t=today(),tc=data.citas.filter(c=>c.fecha===t&&c.estado!=="cancelada"),inc=data.citas.filter(c=>c.fecha===t&&c.estado==="completada").reduce((s,c)=>s+c.total,0),estimado=tc.reduce((s,c)=>s+c.total,0),mantenimientos=reminders().length,hoy=new Date(),cumples=clientGroups().filter(c=>c.cumpleanos&&parseDate(c.cumpleanos).getMonth()===hoy.getMonth()&&parseDate(c.cumpleanos).getDate()===hoy.getDate()).length,hora=hoy.getHours(),saludo=hora<12?"Buenos días":hora<19?"Buenas tardes":"Buenas noches";$("todayCount").textContent=tc.length;$("todayIncome").textContent=money(inc);$("clientCount").textContent=clientGroups().length;$("reminderCount").textContent=mantenimientos;$("dashName").textContent=data.config.nombre;$("assistantGreeting").textContent=`${saludo}, Yuli ☕`;$("assistantSummary").textContent=`Hoy tienes ${tc.length} ${tc.length===1?"cita":"citas"} y un ingreso estimado de ${money(estimado)}.`;$("assistantDetail").textContent=`${mantenimientos} ${mantenimientos===1?"mantenimiento por contactar":"mantenimientos por contactar"} · ${cumples} ${cumples===1?"clienta cumple años":"clientas cumplen años"}.`;const a=data.citas.filter(c=>c.estado==="pendiente"&&dateTime(c)>=new Date()).sort((x,y)=>dateTime(x)-dateTime(y)).slice(0,6);$("upcoming").innerHTML=a.length?a.map(c=>{const d=parseDate(c.fecha);return `<article class="upcoming-row"><div class="date-box"><strong>${String(d.getDate()).padStart(2,"0")}</strong><span>${d.toLocaleDateString("es-PA",{month:"short"}).replace(".","")}</span></div><div><h4>${esc(c.nombre)}</h4><p>${esc(c.servicio)} · ${formatTime(c.hora)}</p></div><strong>${money(c.total)}</strong></article>`}).join(""):'<p class="empty">No hay próximas citas.</p>'}
function buildFortnights(){const o=[],h=new Date();for(let i=0;i<12;i++){const r=new Date(h.getFullYear(),h.getMonth(),h.getDate()-i*15),s=r.getDate()<=15?new Date(r.getFullYear(),r.getMonth(),1):new Date(r.getFullYear(),r.getMonth(),16),e=r.getDate()<=15?new Date(r.getFullYear(),r.getMonth(),15):new Date(r.getFullYear(),r.getMonth()+1,0),v=`${dateText(s)}|${dateText(e)}`;if(!o.some(x=>x.v===v))o.push({v,t:`${s.getDate()}–${e.getDate()} ${s.toLocaleDateString("es-PA",{month:"long",year:"numeric"})}`})}$("fortnightSelect").innerHTML=o.map(x=>`<option value="${x.v}">${x.t}</option>`).join("")}
function renderFinance(){const v=val("fortnightSelect");if(!v)return;const [s,e]=v.split("|").map(parseDate),inRange=c=>{const d=parseDate(c.fecha);return d>=s&&d<=e},done=data.citas.filter(c=>c.estado==="completada"&&inRange(c)),can=data.citas.filter(c=>c.estado==="cancelada"&&inRange(c)),income=done.reduce((a,c)=>a+c.total,0);$("fortnightIncome").textContent=money(income);$("fortnightDone").textContent=done.length;$("fortnightAvg").textContent=money(done.length?income/done.length:0);$("fortnightCanceled").textContent=can.length;const sv={};done.forEach(c=>{sv[c.servicio]??={n:0,t:0};sv[c.servicio].n++;sv[c.servicio].t+=c.total});$("fortnightServices").innerHTML=Object.keys(sv).length?Object.entries(sv).sort((a,b)=>b[1].t-a[1].t).map(([n,x])=>`<div class="summary-row"><strong>${esc(n)}</strong><span>${x.n} citas</span><strong>${money(x.t)}</strong></div>`).join(""):'<p class="empty">No hay datos para esta quincena.</p>';const cl={};done.forEach(c=>{const k=norm(c.nombre);cl[k]??={nombre:c.nombre,n:0,t:0};cl[k].n++;cl[k].t+=c.total});$("fortnightClients").innerHTML=Object.keys(cl).length?Object.values(cl).sort((a,b)=>b.t-a.t).map(x=>`<div class="summary-row"><strong>${esc(x.nombre)}</strong><span>${x.n} visitas</span><strong>${money(x.t)}</strong></div>`).join(""):'<p class="empty">No hay datos para esta quincena.</p>'}
function currentService(){return data.config.servicios.find(s=>s.nombre===val("calcService"))||data.config.servicios[0]}
function calculate(){const s=currentService();if(!s)return;$("lengthGroup").style.display=s.modo==="largo"?"grid":"none";let base=s.modo==="largo"?Number(data.config.largos[val("calcLength")]||0):Number(s.precio||0),sum=base,rows=[{n:s.nombre,v:base}];document.querySelectorAll("#calcExtras input:checked").forEach(i=>{const x=data.config.extras.find(e=>e.id===i.dataset.extra);if(x){sum+=x.precio;rows.push({n:x.nombre,v:x.precio})}});const m=Math.max(0,Number(val("manualExtra")||0));if(m){sum+=m;rows.push({n:"Otro extra",v:m})}const manual=Math.min(100,Math.max(0,Number(val("discount")||0))),cumple=$("birthdayDiscount").checked?Math.min(100,Math.max(0,Number(data.config.descuentoCumple||0))):0,totalDesc=Math.min(100,manual+cumple),dv=sum*totalDesc/100;calcTotal=sum-dv;$("birthdayDiscountText").textContent=`Aplicar ${Number(data.config.descuentoCumple||0)}%`;$("calcTotal").textContent=money(calcTotal);$("calcBreakdown").innerHTML=rows.map(x=>`<div class="breakdown-row"><span>${esc(x.n)}</span><strong>${money(x.v)}</strong></div>`).join("")+(manual?`<div class="breakdown-row"><span>Descuento manual (${manual}%)</span><strong>-${money(sum*manual/100)}</strong></div>`:"")+(cumple?`<div class="breakdown-row"><span>Descuento de cumpleaños (${cumple}%)</span><strong>-${money(sum*cumple/100)}</strong></div>`:"")}
function addService(){const n=prompt("Nombre del nuevo sistema o servicio:")?.trim();if(!n)return;if(data.config.servicios.some(s=>s.nombre.toLowerCase()===n.toLowerCase()))return alert("Ese servicio ya existe.");const byLength=confirm("Aceptar: precio por largo. Cancelar: precio fijo.");let p=0;if(!byLength){const x=prompt("Precio fijo:","25");if(x===null)return;p=Math.max(0,Number(x)||0)}data.config.servicios.push({id:`s${Date.now()}`,nombre:n,modo:byLength?"largo":"fijo",precio:p,fijo:false});save();fillServices(n);renderCatalog();calculate()}
function addExtra(){const n=prompt("Nombre del efecto, diseño o extra:")?.trim();if(!n)return;if(data.config.extras.some(x=>x.nombre.toLowerCase()===n.toLowerCase()))return alert("Ese extra ya existe.");const x=prompt("Precio:","5");if(x===null)return;data.config.extras.push({id:`e${Date.now()}`,nombre:n,precio:Math.max(0,Number(x)||0),fijo:false});save();renderExtras();renderCatalog();calculate()}
function removeService(i){const s=data.config.servicios.find(x=>x.id===i);if(!s||s.fijo)return alert("Los servicios originales no se eliminan.");if(confirm(`¿Eliminar ${s.nombre}?`)){data.config.servicios=data.config.servicios.filter(x=>x.id!==i);save();fillServices();renderCatalog();calculate()}}
function removeExtra(i){const x=data.config.extras.find(e=>e.id===i);if(!x||x.fijo)return alert("Los extras originales no se eliminan.");if(confirm(`¿Eliminar ${x.nombre}?`)){data.config.extras=data.config.extras.filter(e=>e.id!==i);save();renderExtras();renderCatalog();calculate()}}
function editService(i){const s=data.config.servicios.find(x=>x.id===i);if(!s)return;const n=prompt("Nombre del servicio:",s.nombre)?.trim();if(!n)return;const porLargo=confirm("Aceptar: usar precios por largo. Cancelar: usar precio fijo.");let p=s.precio;if(!porLargo){const x=prompt("Precio fijo:",String(s.precio||0));if(x===null)return;p=Math.max(0,Number(x)||0)}s.nombre=n;s.modo=porLargo?"largo":"fijo";s.precio=p;save();fillServices(n);renderCatalog();calculate()}
function editExtra(i){const x=data.config.extras.find(e=>e.id===i);if(!x)return;const n=prompt("Nombre del efecto o extra:",x.nombre)?.trim();if(!n)return;const p=prompt("Precio:",String(x.precio));if(p===null)return;x.nombre=n;x.precio=Math.max(0,Number(p)||0);save();renderExtras();renderCatalog();calculate()}
function renderCatalog(){$("serviceCatalog").innerHTML=data.config.servicios.map(s=>`<div class="catalog-item"><span><strong>${esc(s.nombre)}</strong> · ${s.modo==="largo"?"precio por largo":money(s.precio)}</span><div><button class="edit-catalog" onclick="editService('${s.id}')">Editar</button>${s.fijo?"":`<button onclick="removeService('${s.id}')">Eliminar</button>`}</div></div>`).join("");$("extraCatalog").innerHTML=data.config.extras.map(x=>`<div class="catalog-item"><span><strong>${esc(x.nombre)}</strong> · ${money(x.precio)}</span><div><button class="edit-catalog" onclick="editExtra('${x.id}')">Editar</button>${x.fijo?"":`<button onclick="removeExtra('${x.id}')">Eliminar</button>`}</div></div>`).join("")}
function quoteToAppointment(){const s=currentService(),extras=[...document.querySelectorAll("#calcExtras input:checked")].map(i=>data.config.extras.find(x=>x.id===i.dataset.extra)?.nombre).filter(Boolean);openNew();$("service").value=s.nombre;$("total").value=calcTotal.toFixed(2);$("notes").value=`${s.modo==="largo"?`Largo: ${val("calcLength")}. `:""}${extras.length?`Extras: ${extras.join(", ")}.`:""}`;show("agenda")}
function clearCalc(){$("calcService").selectedIndex=0;$("calcLength").value="corto";document.querySelectorAll("#calcExtras input").forEach(i=>i.checked=false);$("manualExtra").value=0;$("discount").value=0;$("birthdayDiscount").checked=false;calculate()}
function loadConfig(){$("configName").value=data.config.nombre;$("configDays").value=data.config.dias;$("priceShort").value=data.config.largos.corto;$("priceMedium").value=data.config.largos.medio;$("priceLong").value=data.config.largos.largo;$("birthdayPercent").value=Number(data.config.descuentoCumple||0)}
function saveConfig(){data.config.nombre=val("configName").trim()||"YVA STUDIO";data.config.dias=Math.max(1,Number(val("configDays"))||25);data.config.largos={corto:Math.max(0,Number(val("priceShort"))||0),medio:Math.max(0,Number(val("priceMedium"))||0),largo:Math.max(0,Number(val("priceLong"))||0)};data.config.descuentoCumple=Math.min(100,Math.max(0,Number(val("birthdayPercent"))||0));save();refresh();alert("Configuración guardada.")}
function resetCatalog(){if(confirm("¿Restablecer servicios, extras y precios originales?")){const n=data.config.nombre,d=data.config.dias;data.config=JSON.parse(JSON.stringify(BASE));data.config.nombre=n;data.config.dias=d;save();loadConfig();fillServices();renderCatalog();refresh()}}
function deleteAll(){if(confirm("Se eliminarán todas las citas y clientas. ¿Continuar?")&&confirm("Esta acción no se puede deshacer. ¿Eliminar definitivamente?")){data.citas=[];save();refresh()}}
function exportData(){const b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`respaldo-yva-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function refresh(){$("brandName").textContent=data.config.nombre;$("maintenanceText").textContent=`${data.config.dias} días`;document.title=data.config.nombre;renderAppointments();renderClients();renderReminders();renderDashboard();renderFinance();updateCalendar();calculate()}
function $(i){return document.getElementById(i)}function val(i){return $(i).value}function id(){return Date.now()+Math.floor(Math.random()*1e4)}function parseDate(t){const[a,m,d]=t.split("-").map(Number);return new Date(a,m-1,d)}function dateText(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function today(){return dateText(new Date())}function dateTime(c){return new Date(`${c.fecha}T${c.hora||"00:00"}:00`)}function addDays(t,n){const d=parseDate(t);d.setDate(d.getDate()+Number(n));return startDay(d)}function startDay(d){const x=new Date(d);x.setHours(0,0,0,0);return x}function daysBetween(a,b){return Math.max(0,Math.floor((startDay(b)-startDay(a))/864e5))}function formatDate(t){return t?parseDate(t).toLocaleDateString("es-PA",{day:"2-digit",month:"short",year:"numeric"}):"—"}function formatTime(t){if(!t)return"—";const[h,m]=t.split(":").map(Number),d=new Date();d.setHours(h,m,0,0);return d.toLocaleTimeString("es-PA",{hour:"numeric",minute:"2-digit"})}function money(n){return Number(n||0).toLocaleString("en-US",{style:"currency",currency:"USD"})}function norm(t){return String(t||"").trim().toLowerCase().replace(/\s+/g," ")}function state(s){return{pendiente:"Pendiente",completada:"Completada",cancelada:"Cancelada"}[s]||"Pendiente"}function esc(t){const d=document.createElement("div");d.textContent=String(t||"");return d.innerHTML}
Object.assign(window,{editAppointment,completeAppointment,cancelAppointment,deleteAppointment,openHistory,scheduleMaintenance,removeService,removeExtra,editService,editExtra});
